// <auto-generated />
using Designing_API_To_Ready_To_Go_Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Designing_API_To_Ready_To_Go_Database.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20250329204134_SiparisDetayFix")]
    partial class SiparisDetayFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Designing_API_To_Ready_To_Go_Database.Models.Musteriler", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Isim")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Kullanici Adi");

                    b.Property<string>("ParolaH")
                        .HasMaxLength(267)
                        .IsUnicode(false)
                        .HasColumnType("varchar(267)");

                    b.Property<string>("Soyisim")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Musteril__3214EC079FFD8624");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Designing_API_To_Ready_To_Go_Database.Models.SiparisDetay", b =>
                {
                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.Property<int?>("Miktar")
                        .HasColumnType("int");

                    b.HasKey("SiparisId", "UrunId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisDetay");
                });

            modelBuilder.Entity("Designing_API_To_Ready_To_Go_Database.Models.Siparisler", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"));

                    b.Property<string>("MusteriId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SiparisId")
                        .HasName("PK__Siparisl__C3F03BFDE7BA8F4E");

                    b.HasIndex("MusteriId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("Designing_API_To_Ready_To_Go_Database.Models.Urunler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepoMiktari")
                        .HasColumnType("int")
                        .HasColumnName("Depo Miktari");

                    b.Property<int?>("Fiyat")
                        .HasColumnType("int");

                    b.Property<string>("Isim")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Kategori")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Urunler__3214EC077A254878");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("Designing_API_To_Ready_To_Go_Database.Models.SiparisDetay", b =>
                {
                    b.HasOne("Designing_API_To_Ready_To_Go_Database.Models.Siparisler", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .IsRequired()
                        .HasConstraintName("FK__SiparisDe__Sipar__59FA5E80");

                    b.HasOne("Designing_API_To_Ready_To_Go_Database.Models.Urunler", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .IsRequired()
                        .HasConstraintName("FK__SiparisDe__UrunI__5BE2A6F2");

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Designing_API_To_Ready_To_Go_Database.Models.Siparisler", b =>
                {
                    b.HasOne("Designing_API_To_Ready_To_Go_Database.Models.Musteriler", "Musteri")
                        .WithMany("Siparisler")
                        .HasForeignKey("MusteriId")
                        .HasConstraintName("FK__Siparisle__Muste__5070F446");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Designing_API_To_Ready_To_Go_Database.Models.Musteriler", b =>
                {
                    b.Navigation("Siparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
